.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2022 Jari Ahola <aphototool@ahola.me>,
.\"
.TH APHOTOTOOLLIBRE 1 "March  6 2022"

.SH NAME
aphototoollibre \- photo editing application

.SH SYNOPSIS
.B aphototoollibre
.RI [IMAGE_FILE]

.SH DESCRIPTION
.B aphototoollibre
is a photo editing application.
It has graphical user interface for easy to use editing commands.
.PP
If IMAGE_FILE is given as parameter then it will be loaded for editing.
With no IMAGE_FILE the user interface may be used to load image for editing. 

.SH AUTHOR
Written by Jari Ahola.

.SH COPYRIGHT
Copyright © 2021-2022 Jari Ahola. License GPLv3+: Gnu GPL version 3 or later.
.PP
aphototoollibre is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE. See the GNU General Public License for more details.

