name: aphototoollibre
base: core20
version: '1.0.5-3'
summary: Photo editor for Linux
description: |
  A Photo Tool (Libre) is an easy to use basic photo editor.
  Fix and modify your jpeg photos to look even greater.
  Supports several other imageformats also.

grade: stable
confinement: strict
compression: lzo

apps:
  aphototoollibre:
    common-id: aphototoollibre.desktop
    command: usr/bin/aphototoollibre
    extensions:
      - kde-neon
    plugs:
      - home
      - cups-control

parts:
  aphototoollibre:
    source: https://github.com/aphototool/A-Photo-Tool-Libre/archive/refs/tags/v1.0.5-1.tar.gz
    plugin: qmake
    build-packages:
      - qtbase5-dev
    stage-packages:
      - libqt5gui5
      - libqt5widgets5 
      - libqt5core5a
      - libqt5printsupport5
