name: aphototoollibre
base: core24
version: '1.0.7-1'
summary: Photo editor for Linux
description: |
  A Photo Tool (Libre) is an easy to use basic photo editor.
  Fix and modify your jpeg photos to look even greater.
  Supports several other imageformats also.

grade: stable
confinement: strict
compression: lzo

apps:
  aphototoollibre:
    common-id: aphototoollibre.desktop
    command: usr/bin/aphototoollibre
    extensions:
      - kde-neon-6
    plugs:
      - home
      - cups-control

parts:
  aphototoollibre:
    source: https://github.com/aphototool/A-Photo-Tool-Libre/archive/refs/tags/v1.0.7-1-Qt6.tar.gz
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
